# Generated by Django 4.0.6 on 2022-10-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_order_user_id_alter_orderdetail_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
    ]
